# -*- coding: utf-8 -*-
"""CSC480_FinalProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eC_AWdt1a_6uoxlDWeR4qUaFDXkT7cpa
"""

!pip install catboost
!pip install xgboost -U
!pip install optuna

!pip install --upgrade lightgbm

# Imports
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
import missingno as msno
from pathlib import Path
from google.colab import drive
import polars as pl

import json

# Visualization
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, HistGradientBoostingRegressor
from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

import random
from sklearn.ensemble import VotingRegressor

import lightgbm as lgb

from catboost import CatBoostRegressor
import xgboost as xgb
import sys
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBRegressor
import lightgbm as lgb
from lightgbm import LGBMRegressor
from sklearn.model_selection import RandomizedSearchCV
import optuna

## Create functions that will do feature engineering
def generate_features(df_data, df_client, df_gas_prices, df_electricity_prices, df_forecast_weather, df_historical_weather, df_weather_station_to_county_mapping, df_target):
    df_data = (
        df_data.with_columns(pl.col("datetime").cast(pl.Date).alias("date"),)
    )

    df_gas_prices = (
        df_gas_prices.rename({"forecast_date": "date"})
    )

    df_electricity_prices = (
        df_electricity_prices.rename({"forecast_date": "datetime"})
    )

    df_weather_station_to_county_mapping = (
        df_weather_station_to_county_mapping.with_columns(pl.col("latitude").cast(pl.datatypes.Float32), pl.col("longitude").cast(pl.datatypes.Float32))
    )

    df_target_all_type_sum = (
        df_target.group_by(["datetime", "county", "is_business", "is_consumption"]).sum().drop("product_type")
    )

    df_forecast_weather = (
        df_forecast_weather.rename({"forecast_datetime": "datetime"}).filter(pl.col("hours_ahead") >= 24)
        .with_columns(pl.col("latitude").cast(pl.datatypes.Float32), pl.col("longitude").cast(pl.datatypes.Float32),
                      pl.col('datetime').dt.replace_time_zone(None).cast(pl.Datetime("us")),)
        .join(df_weather_station_to_county_mapping, how="left", on=["longitude", "latitude"]).drop("longitude", "latitude")
    )

    df_historical_weather = (
        df_historical_weather
        .with_columns(pl.col("latitude").cast(pl.datatypes.Float32), pl.col("longitude").cast(pl.datatypes.Float32))
        .join(df_weather_station_to_county_mapping, how="left", on=["longitude", "latitude"]).drop("longitude", "latitude")
    )

    df_forecast_weather_date = df_forecast_weather.group_by("datetime").mean().drop("county")
    df_forecast_weather_local = df_forecast_weather.filter(pl.col("county").is_not_null()).group_by("county", "datetime").mean()
    df_historical_weather_date = df_historical_weather.group_by("datetime").mean().drop("county")
    df_historical_weather_local = df_historical_weather.filter(pl.col("county").is_not_null()).group_by("county", "datetime").mean()

    df_data = (
        df_data
        .join(df_gas_prices.with_columns((pl.col("date") + pl.duration(days=1)).cast(pl.Date)), on="date", how="left")
        .join(df_client.with_columns((pl.col("date") + pl.duration(days=2)).cast(pl.Date)), on=["county", "is_business", "product_type", "date"], how="left")
        .join(df_electricity_prices.with_columns(pl.col("datetime") + pl.duration(days=1)), on="datetime", how="left")

        .join(df_forecast_weather_date, on="datetime", how="left", suffix="_fd")
        .join(df_forecast_weather_local, on=["county", "datetime"], how="left", suffix="_fl")
        .join(df_forecast_weather_date.with_columns(pl.col("datetime") + pl.duration(days=7)), on="datetime", how="left", suffix="_fd_7d")
        .join(df_forecast_weather_local.with_columns(pl.col("datetime") + pl.duration(days=7)), on=["county", "datetime"], how="left", suffix="_fl_7d")

        .join(df_historical_weather_date.with_columns(pl.col("datetime") + pl.duration(days=2)), on="datetime", how="left", suffix="_hd_2d")
        .join(df_historical_weather_local.with_columns(pl.col("datetime") + pl.duration(days=2)), on=["county", "datetime"], how="left", suffix="_hl_2d")
        .join(df_historical_weather_date.with_columns(pl.col("datetime") + pl.duration(days=7)), on="datetime", how="left", suffix="_hd_7d")
        .join(df_historical_weather_local.with_columns(pl.col("datetime") + pl.duration(days=7)), on=["county", "datetime"], how="left", suffix="_hl_7d")

        # lag target features (past target values)
        .join(df_target.with_columns(pl.col("datetime") - pl.duration(days=1)).rename({"target": "target_lag_1"}), on=["county", "is_business", "product_type", "is_consumption", "datetime"], how="left")
        .join(df_target.with_columns(pl.col("datetime") - pl.duration(days=2)).rename({"target": "target_lag_2"}), on=["county", "is_business", "product_type", "is_consumption", "datetime"], how="left")
        .join(df_target.with_columns(pl.col("datetime") - pl.duration(days=3)).rename({"target": "target_lag_3"}), on=["county", "is_business", "product_type", "is_consumption", "datetime"], how="left")
        .join(df_target.with_columns(pl.col("datetime") - pl.duration(days=4)).rename({"target": "target_lag_4"}), on=["county", "is_business", "product_type", "is_consumption", "datetime"], how="left")
        .join(df_target.with_columns(pl.col("datetime") - pl.duration(days=5)).rename({"target": "target_lag_5"}), on=["county", "is_business", "product_type", "is_consumption", "datetime"], how="left")

        .join(df_target_all_type_sum.with_columns(pl.col("datetime") - pl.duration(days=1)).rename({"target": "target_lag_1"}), on=["county", "is_business", "is_consumption", "datetime"], suffix="_all_type_sum", how="left")
        .join(df_target_all_type_sum.with_columns(pl.col("datetime") - pl.duration(days=2)).rename({"target": "target_lag_2"}), on=["county", "is_business", "is_consumption", "datetime"], suffix="_all_type_sum", how="left")

        .with_columns(
            pl.col("datetime").dt.ordinal_day().alias("dayofyear"),
            pl.col("datetime").dt.hour().alias("hour"),
            pl.col("datetime").dt.day().alias("day"),
            pl.col("datetime").dt.weekday().alias("weekday"),
            pl.col("datetime").dt.month().alias("month"),
            pl.col("datetime").dt.year().alias("year"),
        )
        .with_columns(
            pl.concat_str("county", "is_business", "product_type", "is_consumption", separator="_").alias("segment"),
        )
        .with_columns(
            (np.pi * pl.col("dayofyear") / 183).sin().alias("sin(dayofyear)"),
            (np.pi * pl.col("dayofyear") / 183).cos().alias("cos(dayofyear)"),
            (np.pi * pl.col("hour") / 12).sin().alias("sin(hour)"),
            (np.pi * pl.col("hour") / 12).cos().alias("cos(hour)"),
        )
        .with_columns(
            pl.col(pl.Float64).cast(pl.Float32),
        )
        .drop("datetime", "hour", "dayofyear")
    )

    return df_data

## Create a pandas datafram from polars combining the y parameter
def to_pandas(X, y=None):
    cat_cols = ["county", "is_business", "product_type", "is_consumption", "segment"]

    if y is not None:
        df = pd.concat([X.to_pandas(), y.to_pandas()], axis=1)
    else:
        df = X.to_pandas()

    df = df.set_index("row_id")
    df[cat_cols] = df[cat_cols].astype("category")

    return df

drive.mount('/content/drive')

folder_path = '/content/drive/My Drive/Colab Notebooks/predict-energy-behavior-of-prosumers'
# all_files is a list of all the
all_files = os.listdir(folder_path)
print(all_files)

# Read CSVs and parse relevant date columns
df_train = pl.read_csv(folder_path + "/train.csv", try_parse_dates=True)
df_client = pl.read_csv(folder_path + "/client.csv", try_parse_dates=True)
df_historical_weather = pl.read_csv(folder_path + "/historical_weather.csv", try_parse_dates=True)
df_forecast_weather = pl.read_csv(folder_path + "/forecast_weather.csv", try_parse_dates=True)
df_electricity = pl.read_csv(folder_path + "/electricity_prices.csv", try_parse_dates=True)
df_gas_prices = pl.read_csv(folder_path + "/gas_prices.csv", try_parse_dates=True)
df_weather_station_to_county_mapping = pl.read_csv(folder_path + "/weather_station_to_county_mapping.csv", try_parse_dates=True)

# Helper functions
def display_df(df, name):
    '''Display df shape and first row '''
    print(f'{name} data has {df.shape[0]} rows and {df.shape[1]} columns. \n ===> First row:')
    display(df.head(2))

display_df(df_train, 'train')
print('\n\n')
display_df(df_client, 'client')
print('\n\n')
display_df(df_historical_weather, 'historical weather')
print('\n\n')
display_df(df_forecast_weather, 'forecast weather')
print('\n\n')
display_df(df_electricity, 'electricity prices')
print('\n\n')
display_df(df_gas_prices, 'gas prices')
print('\n\n')
display_df(df_weather_station_to_county_mapping, 'weather station to county mapping')

## Should be sensible to create a df_full that contains all the relevant features
## Thanks to kaggle code for helping with the feature engineering aspect, see references on report paper

## Define important columns
data_cols = ['target', 'county', 'is_business', 'product_type', 'is_consumption', 'datetime', 'row_id']
client_cols = ['product_type', 'county', 'eic_count', 'installed_capacity', 'is_business', 'date']
gas_prices_cols = ['forecast_date', 'lowest_price_per_mwh', 'highest_price_per_mwh']
electricity_prices_cols = ['forecast_date', 'euros_per_mwh']
forecast_weather_cols = ['latitude', 'longitude', 'hours_ahead', 'temperature', 'dewpoint', 'cloudcover_high', 'cloudcover_low', 'cloudcover_mid', 'cloudcover_total', '10_metre_u_wind_component', '10_metre_v_wind_component', 'forecast_datetime', 'direct_solar_radiation', 'surface_solar_radiation_downwards', 'snowfall', 'total_precipitation']
historical_weather_cols = ['datetime', 'temperature', 'dewpoint', 'rain', 'snowfall', 'surface_pressure','cloudcover_total','cloudcover_low','cloudcover_mid','cloudcover_high','windspeed_10m','winddirection_10m','shortwave_radiation','direct_solar_radiation','diffuse_radiation','latitude','longitude']
location_cols = ['longitude', 'latitude', 'county']
target_cols = ['target', 'county', 'is_business', 'product_type', 'is_consumption', 'datetime']

## Importing only specified columns
df_train = df_train[data_cols]
df_client = df_client[client_cols]
df_historical_weather = df_historical_weather[historical_weather_cols]
df_forecast_weather = df_forecast_weather[forecast_weather_cols]
df_electricity = df_electricity[electricity_prices_cols]
df_gas_prices = df_gas_prices[gas_prices_cols]
df_weather_station_to_county_mapping = df_weather_station_to_county_mapping[location_cols]
df_target = df_train.select(target_cols)

"""## EDA and Graphing out the data to see what we are dealing with.

"""

print(df_train["target"].describe())
target_pd = df_train.select("target").to_pandas()["target"]

plt.figure(figsize=(6,4))
plt.hist(target_pd, bins=50)
plt.title("Distribution of target")
plt.xlabel("target")
plt.ylabel("frequency")
plt.show()

# Boxplot by product_type
pt = df_train.select(["product_type", "target"]).to_pandas()
plt.figure(figsize=(6,4))
pt.boxplot(column="target", by="product_type", showfliers=False)
plt.suptitle("")
plt.title("Target by product_type")
plt.xlabel("product_type")
plt.ylabel("target")
plt.show()

daily_avg = (
    df_train
    .with_columns([
        pl.col("datetime").dt.date().alias("date")
    ])
    .group_by("date")
    .agg(pl.col("target").mean().alias("avg_target"))
    .sort("date")
)
# convert for plotting
daily_pd = daily_avg.to_pandas().set_index("date")

daily_pd["avg_target"].plot(figsize=(10,4), title="Daily Average Target")
plt.ylabel("avg target")
plt.show()

df_weather_station_to_county_mapping = df_weather_station_to_county_mapping.with_columns(
    pl.lit(5).alias('size')
)
fig = px.scatter_mapbox (
    df_weather_station_to_county_mapping,
    lat = 'latitude',
    lon = 'longitude',
    color = 'county',
    size = 'size',
    zoom =6,
    title='Weather Stations Locations'
)
fig.update_layout(mapbox_style='open-street-map')
fig.update_layout(margin={'r':0,'t':30,'l':0,'b':0})
fig.show()

county = 0
is_business = 0
is_consumption = 1

df_plot = df_train.filter(
    (pl.col('county') == county) &
    (pl.col('is_business') == is_business) &
    (pl.col('is_consumption') == is_consumption)
)


fig = px.line(
    df_plot,
    x="datetime",
    y="target",
    color="product_type",
    title=f"Target for county={county}, is_business={is_business}, is_consumption={is_consumption}"
)
fig.show()

## From the graph below it can be seen that there is a notable trend of an increase in
## target values of product 3 during the month of January. Check to see if this is consistent
## across all counties and not just county 0

product_type = 3
is_business = 0
is_consumption = 1

df_plot = df_train.filter(
    (pl.col('is_business') == is_business) &
    (pl.col('is_consumption') == is_consumption) &
    (pl.col('product_type') == product_type)
)

fig = px.line(
    df_plot,
    x="datetime",
    y="target",
    color="county",
    color_discrete_sequence=px.colors.qualitative.Set1,
    title=f"Target for is_business={is_business}, is_consumption={is_consumption}, product_type={county}"
)
fig.show()

"""Create a full merged dataset, df_train_features that we will be working off of for the rest of the code, serves as our master dataframe"""

df_train, y = df_train.drop("target"), df_train.select("target")

df_train_features = generate_features(df_train, df_client, df_gas_prices, df_electricity, df_forecast_weather, df_historical_weather, df_weather_station_to_county_mapping, df_target)

df_train_features = to_pandas(df_train_features, y)

# a little proportion of target values are null
df_train_features = df_train_features[df_train_features['target'].notnull()]

# UNCOMMENT FOR TEMPORAL DATA ANALYSIS AS IMPUTING FROM HERE CAUSES SESSION CRASH IN GOOGLE COLAB
# ONCE DONE WITH DATA ANALYSIS, AND HEADING INTO MODEL TRAINING, COMMENT THIS PART OUT AND RE-RUN CELLS UP TO AND INCLUDING THIS ONE

# df_train_features = df_train_features[df_train_features.year >= 2022]

# import gc
# del df_train, df_client, df_gas_prices, df_electricity, df_forecast_weather, df_historical_weather, df_weather_station_to_county_mapping, df_target
# gc.collect()

for col in df_train_features.columns:
  print(f"{col} , Example value: = {df_train_features[col].iloc[0]}")
print(df_train_features.shape)
print(df_train_features.head())

"""## Temporal data analysis

"""

random.seed(42)
segment_list = df_train_features["segment"].unique()
segment_list = random.sample(sorted(segment_list), 10)
example_df =df_train_features[np.isin(df_train_features.segment, segment_list)]

## Do FFT Computation, which is useful to convert time-domain into frequency domain, allowing us to view dominant frequencies
import plotly.graph_objects as go
# Define periods in hours that we wish to analyze
periods = {'Annual' : 365 * 24, 'Semiannual' : (362/2) * 24, 'Quarterly' : (365/4) * 24, 'Monthly' : 30 * 24, 'Biweekly':14 *24, 'Weekly' : 7 *24, 'Halfweek' : (7/2) * 24, 'Daily': 24, 'Halfday':12}
frequencies_for_periods = {k:1 /v for k,v in periods.items()}

fig = go.Figure()
# View the x-axes on a logarithmic scale to have less-skewed data visualization
fig.update_xaxes(type='log')

for i, segment in enumerate(sorted(segment_list)):
  segment_data = example_df[example_df["segment"] == segment]['target']
  fft_values = np.fft.fft(segment_data)
  frequencies = np.fft.fftfreq(len(fft_values), d=1)
  magnitudes = np.abs(fft_values)[frequencies > 0]
  normalized_magnitudes = magnitudes / np.max(magnitudes)
  positive_freqs = frequencies[frequencies > 0]
  #Annual/Semiannual frequencies might not reveal any potential information/fluctuation as shorter periods might provide
  valid_freqs = positive_freqs[positive_freqs > frequencies_for_periods['Semiannual']]
  valid_magnitudes = normalized_magnitudes[positive_freqs > frequencies_for_periods['Semiannual']]

  #Offset each segment's spectrum for clarity
  offset_magnitudes = valid_magnitudes + i

  fig.add_trace(go.Scatter(x=valid_freqs, y = offset_magnitudes, mode='lines', name=f'Segment {segment}'))

fig.update_layout(
    title='Magnitude vs Frequency Spectra of target values by hours',
    xaxis_title='Frequency',
    yaxis_title='Normalized magnitude + offset',
    xaxis=dict(tickvals=list(frequencies_for_periods.values()), ticktext=list(frequencies_for_periods.keys())),
    showlegend=True
)
fig.show()

"""It can be seen from the above that we have a high correlation of target with daily and halfday frequencies and some weak patterns between weekly.
This leads me to believe that features that change daily, like wind/temperature etc might play a big part.
"""

## FFT on temperature, solar radiation, dewpoint etc.
def fft_plots(name):
  fig = go.Figure()

  #Convert x axes into log scale
  fig.update_xaxes(type='log')

  segment_data = df_train_features[df_train_features["segment"] == '0_0_1_1'][name]
  #print(segment_data)
  fft_values = np.fft.fft(segment_data)
  frequencies = np.fft.fftfreq(len(fft_values), d=1)
  magnitudes = np.abs(fft_values)[frequencies > 0]

  positive_freqs = frequencies[frequencies > 0]

  valid_freqs = positive_freqs[positive_freqs > frequencies_for_periods['Semiannual']]
  valid_magnitudes = magnitudes[positive_freqs > frequencies_for_periods['Semiannual']]

  # print(valid_freqs)
  # print(valid_magnitudes)

  fig.add_trace(go.Scatter(x=valid_freqs, y = valid_magnitudes, mode='lines', name=f'0_0_1_1'))
  #  Customize the plot layout
  fig.update_layout(
  title=f'{name} frequency spectrum',
  xaxis_title='Frequency',
  yaxis_title='Magnitude',
  xaxis=dict(tickvals=list(frequencies_for_periods.values()), ticktext=list(frequencies_for_periods.keys())),
  showlegend=True,
  )

  # Show the plot
  fig.show()

plot_list = ['temperature', 'direct_solar_radiation', 'dewpoint', 'cloudcover_total', 'highest_price_per_mwh']

for i in plot_list:
  fft_plots(i)

"""## Baseline modeling with and without PCA and with/without imputation"""

# Try pca on the features to see if we could make a difference.
pca_df = df_train_features;

exclude_cols = [
    'date', 'segment',  # time strings or IDs
    'target'
]

pca_df = pca_df.drop(columns = exclude_cols)
categorical_cols = ['county', 'is_business', 'product_type', 'is_consumption']
pca_df[categorical_cols] = pca_df[categorical_cols].astype('category')
pca_numeric = pca_df.select_dtypes(include=['number'])
#Standardize data, Apply imputation. (because I caught an error for NaN values before)
pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),  # fill NaNs
    ('scaler', StandardScaler()),                 # standardize
    ('pca', PCA(n_components=0.95))               # apply PCA

])

pca_applied = pipeline.fit_transform(pca_numeric)
print("Original shape:", pca_numeric.shape)
print("PCA reduced shape:", pca_applied.shape)

plt.plot(range(1, 50), pipeline.named_steps['pca'].explained_variance_ratio_)
plt.xlabel('Principal Component Index')
plt.ylabel('Explained Variance Ratio')
plt.title('PCA Explained Variance')
plt.grid(True)
plt.show()

"""Can observe that variability is mostly explained by the first 10-15 components After about 10-15 PC, we begin getting diminishing returns."""

pca_model = pipeline.named_steps['pca']

# Obtain the features that contribute most to the PC
feature_names = pca_numeric.columns

pc_df = pd.DataFrame(pca_model.components_, columns=feature_names, index=[f'PC{i+1}' for i in range(pca_model.n_components_)])

# View top contributing features for PC1
top_pc1 = pc_df.loc['PC1'].abs().sort_values(ascending=False).head(15)
print("Top 15 features contributing to PC1:")
print(top_pc1)

df_pca = pd.DataFrame(pca_applied, columns=[f'PC{i+1}' for i in range(pipeline.named_steps['pca'].n_components_)])
df_final = pd.concat([
    df_pca.reset_index(drop=True),
    df_train_features[['segment','target']].reset_index(drop=True)
], axis=1)

df_final

## We can try to come up with a model with PCA and without PCA
## Have to one-hot-encode segments for dummy/baseline models but will not need to do that for advanced models like lightGBM
X = df_final.drop(columns=['target']).copy()
le = LabelEncoder()
X['segment'] = le.fit_transform(df_final['segment'])  # assigns 0,1,2,... to each unique segment
y = df_final['target']

from sklearn.model_selection import train_test_split

# Split into 70% train and 30% validation
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.3, random_state=42
)

print(f"Train: {X_train.shape}, Val: {X_val.shape}")

models = {
    'DummyMean': DummyRegressor(strategy='mean'),
    'LinearRegression': LinearRegression(),
    'HistGradientBoosting': HistGradientBoostingRegressor(random_state=42),
}

# Train and evaluate using MAE
for name, model in models.items():
    model.fit(X_train, y_train)
    preds = model.predict(X_val)
    mae = mean_absolute_error(y_val, preds)
    r2 = r2_score(y_val, preds)
    print(f"{name}: MAE = {mae:.4f}, R² = {r2:.4f}")

# import gc
# del X_train, X_val, y_train, y_val, X, y, df_final, df_pca, pc_df, pca_model, pca_df, pca_numeric, pca_applied
# gc.collect()

## Try without PCA and see if it hurts/improves performance
exclude_cols = [
    'date', 'target'
]

imputer = SimpleImputer(strategy='mean')
le = LabelEncoder()
X_raw = df_train_features.drop(columns=exclude_cols)
y_raw = df_train_features['target']

X_raw['segment'] = le.fit_transform(X_raw['segment'])

X_raw_imputed = pd.DataFrame(imputer.fit_transform(X_raw), columns=X_raw.columns)

X_train_raw, X_val_raw, y_train_raw, y_val_raw = train_test_split(X_raw_imputed, y_raw, test_size=0.3, random_state=42)

models = {
    'DummyMean': DummyRegressor(strategy='mean'),
    'LinearRegression': LinearRegression(),
    'HistGradientBoosting': HistGradientBoostingRegressor(random_state=42)
}

for name, model in models.items():
    model.fit(X_train_raw, y_train_raw)
    preds_val = model.predict(X_val_raw)

    mae_val = mean_absolute_error(y_val_raw, preds_val)
    r2_val = r2_score(y_val_raw, preds_val)

    print(f"{name} (Raw Features):")
    print(f"  Val MAE = {mae_val:.4f}, R² = {r2_val:.4f}")

# import gc
# del X_raw, y_raw, X_raw_imputed, X_train_raw, X_val_raw, y_train_raw, y_val_raw
# gc.collect()

"""Up till this point, a brief report of the things that have been tried: PCA was definitely something that seemed an interesting option given the abundance of features in my dataset. Also, since time series data has a good reliance on lagged feature values (evident from prominent features shown in PCA analysis) it would seem a bit sensible to only include the most recent data. Hence, I tried a number of combinations of PCA/non-PCA with recent/entire dataset (recent data excludes data before and up to 2022). After trying out the dataset modifications with some simple baseline models with imputations, it can be decided that keeping the entire dataset, along with the original features, does yield the better MAE score. From here on, with the baseline models set and EDA done, we can move on to more advanced models to help reduce the MAE more"""

## Make a final train/test split with a validation set
exclude_cols = [
    'date', 'target'
]

imputer = SimpleImputer(strategy='mean')
le = LabelEncoder()
X = df_train_features.drop(columns=exclude_cols)
y = df_train_features['target']

# First split into train (70%) and temp (30%)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Split temp into validation (15%) and test (15%)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42
)

print(f"Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")

# import gc
# del X, y, X_temp, y_temp
# gc.collect()

clf =  xgb.XGBRegressor (
    enable_categorical=True,
    objective='reg:absoluteerror',
    n_estimators = 1500,
    early_stopping_rounds = 100
)

clf.fit(X = X_train, y = y_train, eval_set = [ (X_train, y_train), (X_val, y_val)], verbose=True)

drive.mount('/content/drive')

clf.save_model("/content/drive/MyDrive/xgb_model.json")

# As a dictionary
importance_dict = clf.get_booster().get_score(importance_type='gain')
feat_imp_df = pd.DataFrame({
    'Feature': list(importance_dict.keys()),
    'Importance': list(importance_dict.values())
}).sort_values(by='Importance', ascending=False)

print(feat_imp_df.head(15))  # Top 15 most important

# Plot top features by importance
xgb.plot_importance(clf, max_num_features=20, importance_type='gain')
plt.title("Top 20 Feature Importances (by Gain)")
plt.show()

results = clf.evals_result()
train_mae, val_mae = results["validation_0"]["mae"], results["validation_1"]["mae"]
x_values = range(0, len(train_mae))
fig, ax = plt.subplots(figsize=(8,4))
ax.plot(x_values, train_mae, label="Train MAE")
ax.plot(x_values, val_mae, label="Validation MAE")
ax.legend()
plt.ylabel("MAE Loss")
plt.title("XGBoost MAE Loss")
plt.show()

# Make predictions on the test set
clf = XGBRegressor()
clf.load_model("/content/drive/MyDrive/xgb_model.json")

y_pred = clf.predict(X_test)

# # Calculate the MAE
mae = mean_absolute_error(y_test, y_pred)

print(f"Test MAE: {mae:.4f}")

## Hyperparameter tuning for LightGBM model: Takes an incredible amount of time and hence is commented out
##

# def objective(trial):
#     params = {
#         "objective": "regression",
#         "metric": "mae",
#         "verbosity": 2,
#         "boosting_type": "gbdt",
#         "n_estimators": 1500,
#         "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2),
#         "num_leaves": trial.suggest_int("num_leaves", 20, 100),
#         "min_child_samples": trial.suggest_int("min_child_samples", 5, 30),
#         "subsample": trial.suggest_float("subsample", 0.5, 1.0),
#         "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
#     }
#     model = lgb.LGBMRegressor(**params)
#     model.fit(X_train, y_train, eval_set=[(X_val, y_val)])
#     preds = model.predict(X_val)
#     return mean_absolute_error(y_val, preds)

# study = optuna.create_study(direction="minimize")
# study.optimize(objective, n_trials=15)

# print("Best hyperparameters:", study.best_params)

## Final hyperparameters after running the code above: {'learning_rate': 0.1712627595928929, 'num_leaves': 88, 'min_child_samples': 30, 'subsample': 0.7021031659875752, 'colsample_bytree': 0.5216860428834887}

final_model = lgb.LGBMRegressor(
    objective="regression",
    metric="mae",
    boosting_type="gbdt",
    n_estimators=1500,
    learning_rate=0.1712627595928929,
    num_leaves=88,
    min_child_samples=30,
    subsample=0.7021031659875752,
    colsample_bytree=0.5216860428834887,
    random_state=42
)

final_model.fit(
    X= X_train, y = y_train,
    eval_set=[(X_train, y_train), (X_val, y_val)],
)

importances = final_model.feature_importances_
feature_names = final_model.feature_name_

# Combine into a DataFrame
import pandas as pd
feat_df = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values(by="importance", ascending=False)
plt.figure(figsize=(10, 6))
top_n = 20
plt.barh(feat_df["feature"][:top_n][::-1], feat_df["importance"][:top_n][::-1])
plt.xlabel("Importance")
plt.title(f"Top {top_n} Feature Importances (LightGBM)")
plt.tight_layout()
plt.show()

# import joblib
# joblib.dump(final_model, "/content/drive/MyDrive/lgbm_tuned_model.pkl")

y_pred = final_model.predict(X_test)

print("Test MAE:", mean_absolute_error(y_test, y_pred))